version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: *******
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  app:
    image: lab8
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: *******
    depends_on:
      - db
    ports:
      - "8080:8080"
